export const FaqList = [
  {
    id: "headingOne",
    controls: "collapseOne",
    expanded: true,
    btnClass: "",
    contentClass: "show",
    title: "What services does KPM Plumbing & Heating offer?",
    details: `We provides a comprehensive range of services, including plumbing repairs, heating installations, emergency services, pipe installations, and proactive maintenance plans. Our skilled professionals cater to both residential and commercial needs.`,
  },
  {
    id: "headingTwo",
    controls: "collapseTwo",
    expanded: false,
    btnClass: "collapsed",
    contentClass: "",
    title: "Are your services available for emergencies?",
    details: `Yes, we understand that plumbing and heating emergencies can happen anytime. KPM Plumbing & Heating offers 24/7 emergency services to address urgent issues promptly.`,
  },
  {
    id: "headingThree",
    controls: "collapseThree",
    expanded: false,
    btnClass: "collapsed",
    contentClass: "",
    title: "Do you offer maintenance plans?",
    details: `Absolutely. We believe in proactive care for your plumbing and heating systems. Explore our maintenance plans designed to prevent issues, enhance system efficiency, and extend the lifespan of your equipment.`,
  },
  {
    id: "headingFour",
    controls: "collapseFour",
    expanded: false,
    btnClass: "collapsed",
    contentClass: "",
    title: "Can you handle both residential and commercial projects?",
    details: `Yes, our team is experienced in handling projects of various scales, from residential plumbing repairs to large-scale commercial heating installations. We tailor our services to meet the unique requirements of each client.`,
  },
  {
    id: "headingFive",
    controls: "collapseFive",
    expanded: false,
    btnClass: "collapsed",
    contentClass: "",
    title: "What areas does KPM serve?",
    details: `We are based in Burnaby, BC, and proudly serves the surrounding areas. Contact us to discuss your location, and we’ll be happy to assist you.`,
  },
];
